matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      language: generic
      env: CFLAGS="-Werror -coverage"

install:
  - brew update
  - brew install pkg-config || true
  - brew install cairo || true
  - export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
  - brew unlink python@2 || true
  - brew install python || true
  - python3 -m pip install virtualenv
  - virtualenv ../venv -p python3
  - source ../venv/bin/activate
  - python -m pip install --upgrade setuptools
  - python -m pip install --upgrade pytest flake8 "sphinx<3" sphinx_rtd_theme coverage codecov hypothesis attrs
  - python -m pip install --upgrade mypy || true

script:
  - python -m coverage run --branch setup.py test
  - python -m codecov --required || true
  - python -m flake8 .
  - python setup.py sdist
  - python setup.py bdist
  - python setup.py install --root=_root
  - python setup.py install --root="$(pwd)"/_root_abs
  - python setup.py bdist_egg
  - python setup.py bdist_wheel
  - python setup.py install --root=_root_setup
  - python -m pip install .
  - python -m sphinx -W -a -E -b html -n docs docs/_build