jobs:
  - job: MSVC
    timeoutInMinutes: 60
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        Python38-x64:
          python.version: '3.8'
          python.arch: 'x64'
        Python37-x64:
          python.version: '3.7'
          python.arch: 'x64'
        Python37-x86:
          python.version: '3.7'
          python.arch: 'x86'
        Python36-x64:
          python.version: '3.6'
          python.arch: 'x64'
        Python35-x86:
          python.version: '3.5'
          python.arch: 'x86'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: '$(python.arch)'
      - script: |
          choco install 7zip wget
        displayName: Install Dependencies
      - script: |
          call .azure-pipelines\msvc.bat
        displayName: Build & Test
        env:
          MSVC_PLATFORM: $(python.arch)
          CODECOV_TOKEN: $(CODECOV_TOKEN)
          CODECOV_BRANCH: $(Build.SourceBranchName)
          PYTHON: python
