name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.platform_id }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            platform_id: win_amd64
            cairo_plat: x64
          - os: windows-2019
            platform_id: win32
            cairo_plat: x86
          - os: windows-2019
            platform_id: win_arm64
            cairo_plat: arm64

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_ARCHS_WINDOWS: "x86 ARM64 AMD64"
          CIBW_BEFORE_BUILD: "python {package}/.ci/download-cairo-win32.py ${{ matrix.cairo_plat }}"
          CIBW_BUILD: cp38-${{ matrix.platform_id }} cp39-${{ matrix.platform_id }} cp310-${{ matrix.platform_id }} cp311-${{ matrix.platform_id }} cp312-${{ matrix.platform_id }}
          CIBW_TEST_REQUIRES: pytest hypothesis attrs
          CIBW_TEST_COMMAND: bash {package}/.ci/test-wheels.sh {package}
          CIBW_TEST_SKIP: "*-win_arm64"
          CIBW_ENVIRONMENT_WINDOWS: PKG_CONFIG_PATH='${{ github.workspace }}/cairo-prebuild/lib/pkgconfig' PKG_CONFIG='${{ github.workspace }}/cairo-prebuild/bin/pkgconf.exe'

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
