name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        bitness: [32, 64]
        include:
          # Run 32 and 64 bit version in parallel for Windows
          - os: windows-2019
            bitness: 64
            platform_id: win_amd64
          - os: windows-2019
            bitness: 32
            platform_id: win32

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.0
        env:
          CIBW_BEFORE_BUILD: "python {package}/tools/download-cairo-win32.py"
          CIBW_BUILD: cp37-${{ matrix.platform_id }} cp38-${{ matrix.platform_id }} cp39-${{ matrix.platform_id }} cp310-${{ matrix.platform_id }} cp311-${{ matrix.platform_id }}
          CIBW_TEST_REQUIRES: pytest hypothesis attrs
          CIBW_TEST_COMMAND: bash {package}/tools/test-wheels.sh {package}
          CIBW_ENVIRONMENT_WINDOWS: PKG_CONFIG_PATH='${{ github.workspace }}/cairo-prebuild/lib/pkgconfig' PKG_CONFIG='${{ github.workspace }}/cairo-prebuild/bin/pkgconf.exe'

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
